x-env: &env
  KAGGLE_USERNAME: &KAGGLE_USERNAME ${KAGGLE_USERNAME}
  KAGGLE_KEY: &KAGGLE_KEY ${KAGGLE_KEY}

services:
  app:
    build: .
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
    environment:
      <<: *env
    tty: true
